[package]
name = "rust-omop"
version = "0.1.0"
edition = "2021"
rust-version = "1.63"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ballista = { version = "0.11.0" }
datafusion = { worksapce = true }
tokio = "1.0"
